# Sitzung 2: Einführung in Python

In dieser ersten Sitzung möchten wir Sie vertraut machen mit dem Aufbau von Python. Hierzu verwenden wir Jupyter Notebook, welches durch Google Colab in der Cloud gehostet wird. Sie können die Jupyter Notebooks der einzelnen Sitzungen auch sehr gerne herunterladen, wenn Sie sich keinen Google Account zulegen möchten. Alternativ werden wir versuchen, Ihnen die Dateien mitsamt Datensatz über StudIP bereitzustellen. In dem Fall empfehlen wir Ihnen, wie auf den Folien beschrieben, die Benutzung von Anaconda.

Quelle der Sitzung: Mayer, Python one-liners.

Wichtig:
- der Code in einer Zeile wird mir SHIFT + ENTER ausgeführt.
- Das #-Zeichen am Anfang führt dazu, dass der folgende Code in einen "Kommentar" verwandelt wird. Dies bedeutet, dass Jupyter Notebook den Code nicht länger ausführt.
- Die Zahl hinter In und Out [ZAHL] steht für die Position des Codes während der Sitzung. Ein Jupyter Notebook läuft NICHT notwendigerweise von oben nach unten ab.

### Einfache mathematische Rechnungen

WICHTIG:
1. Sie führen Code mit Hilfe von Shift-Enter aus
2. Jede Ausführung wird mit einer Zahl davor gekennzeichnet. Dies ermöglicht die Nachverfolgbarkeit bei der Ausführung von Code.


In [1]:
1

1

In [2]:
1+2

3

In [1]:
100 + 78

178

In [2]:
a = 3

In [3]:
a

3

In [4]:
a*a

9

In [5]:
b = 2

In [6]:
a+b

5

In [7]:
a*b

6

In [8]:
a/b

1.5

In [9]:
a-b

1

In [10]:
a ** 3 # 3*3*3

27

In [11]:
e = 5

In [12]:
e - 3

2

In [13]:
e - 5

0

### Arbeiten mit Text / Strings

In [14]:
c = "Hallo"

In [17]:
Hallo = "Hallo"

In [15]:
c

'Hallo'

In [18]:
Hallo

'Hallo'

In [19]:
d = "Studierende"

In [20]:
c

'Hallo'

In [21]:
d

'Studierende'

In [22]:
c+d

'HalloStudierende'

In [23]:
c + " " + d

'Hallo Studierende'

In [24]:
c.upper()

'HALLO'

In [25]:
c.lower()

'hallo'

In [26]:
d

'Studierende'

In [25]:
d.count('e')

3

### Arbeiten mit Listen

Listen werden wir in späteren Sitzungen noch sehr viel benötigen. Um eine Liste zu erstellen verwenden Sie eckige Klammern [ ].

In [27]:
list = [1,2,3]

In [28]:
list

[1, 2, 3]

In [29]:
a * list

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [30]:
list.remove(2)

In [31]:
list

[1, 3]

In [32]:
list.append(2)

In [33]:
list

[1, 3, 2]

In [34]:
list.sort()

In [35]:
list

[1, 2, 3]

In [36]:
list.reverse()

In [37]:
list

[3, 2, 1]

In [38]:
4 in list

False

In [39]:
3 in list

True

In [40]:
len(list)

3

### Logische Operatoren

In dieser kurzen Abschnitt behandeln wir sogenannte logische Operatoren. Hiermit kann man feststellen, ob eine Aussage z.B. wahr oder falsch ist.

In [41]:
x = True

In [42]:
y = False

In [43]:
x and y

False

In [44]:
x or y

True

In [45]:
not y

True

In [46]:
e == 6

False

In [47]:
e == 5

True

### Importieren von libraries und Arbeit in numpy

Abschließend wollen wir Ihnen noch ein wenig einige der wichtigsten Grundfunktionen von Python zeigen: das importieren von libraries und packages. Im Internet existiert eine Vielzahl von Möglichkeiten, die frei zugängliche Arbeit anderer über sogenannte libraries für sich zu nutzen. Heute importieren und arbeiten wir mit "numpy", eine der wichtigsten DataScience libraries in Python.

Jede library, package oder modul wird (meistens) durch eines der folgenden Schemata importiert und für Sie nutzbar gemacht:
- import XXX
- import XXX as X
- from XXX import X

WICHTIG: Es existieren häufig ausführliche Dokumentationen und Beispiele der jeweiligen Anwendungen im Internet. Sie können den dort gezeigten Code kopieren und damit selbstständig üben.

In [48]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [49]:
import numpy as np

Numpy arbeitet mit sogenannten arrays um Berechnungen durchzuführen. Numpy arrays besitzen dabei mehrere Dimensionen, abhängig von ihrem Aufbau. Ein ein-dimensionaler numpy array entspricht dabei einer einfachen Liste von Zahlen.

In [50]:
m = np.array([0,1,0])

In [51]:
m

array([0, 1, 0])

Mehrdimensionale Arrays bestehen vereinfacht gesagt aus mehr als einer Liste, also einer Reihe von Listen. Mehrdimensionale Arrays in Numpy bieten den Vorteil, dass sie schnellere Berechnungen erlauben und Anwendungen aus der Numpy-Library bietet.

In [52]:
n = np.array([[1,1,1],
            [0,0,0],
            [1,1,1]])

In [53]:
n

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [54]:
o = np.array([[0,0,0],
             [5,5,5],
             [0,0,0]])

In [55]:
n+o

array([[1, 1, 1],
       [5, 5, 5],
       [1, 1, 1]])

In [56]:
n*o

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
np.max(n)

1

In [58]:
np.max(o)

5

In [59]:
np.min(n)

0

In [60]:
np.min(o)

0

In [61]:
np.max(o)

5

In [62]:
p = np.array([10,11,12,13,14,15,16,17,18,19])

In [63]:
p

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
p[0]

10

In [64]:
p[1]

11

In [65]:
p[2]

12

In [66]:
p[0:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
p[1:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
p[:1]

array([10])

In [69]:
p[:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [70]:
p[2:8]

array([12, 13, 14, 15, 16, 17])

In [71]:
p[0:2]

array([10, 11])